//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pscopy.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PSCOPY_DIALOG               102
#define IDS_COULD_NOT_READ_DIRECTORY    102
#define IDR_HTML_DLGELEVATE             103
#define IDS_ELEVATION_REQUIRED_TO_DELETE_FOLDER 103
#define IDS_ELEVATION_REQUIRED_TO_READ_FOLDER 104
#define IDS_ELEVATION_REQUIRED_TO_MOVE_FILE 105
#define IDS_ELEVATION_REQUIRED_TO_COPY_FILE 106
#define IDS_PROJNAME                    107
#define IDS_ELEVATION_REQUIRED_TO_DELETE_FILE 108
#define IDS_ELEVATION_REQUIRED_TO_CREATE_FILES_IN_FOLDER 109
#define IDS_TOOLTIP_PASTE               110
#define IDS_MOVE_DEST_IS_SUBFOLDER_OF_SOURCE 110
#define IDS_COPY_DEST_IS_SUBFOLDER_OF_SOURCE 111
#define IDS_MB_SUFFIX                   118
#define IDS_KB_PER_SEC_SUFFIX           119
#define IDS_PREPARING_TO_COPY_FILES     120
#define IDS_PREPARING_TO_MOVE_FILES     121
#define IDS_COPYING_FILES               122
#define IDS_MOVING_FILES                123
#define IDS_PREPARING_TO_DELETE_FILES   124
#define IDS_DELETING_FILES              125
#define IDS_COULD_NOT_COPY_FILE         126
#define IDS_COULD_NOT_MOVE_FILE         127
#define IDR_MAINFRAME                   128
#define IDS_COULD_NOT_DELETE_FILE       128
#define IDD_OVERWRITE_PROMPT            129
#define IDS_COULD_NOT_CREATE_DIRECTORY  129
#define IDD_FAILED_FILES                130
#define IDS_COULD_NOT_REMOVE_DIRECTORY  130
#define IDD_DIALOG_PROGRESS             131
#define IDS_WARN_COULD_NOT_REMOVE_DIR   131
#define IDS_WARN_COULD_NOT_REMOVE_FILE  132
#define IDD_ELEVATE                     132
#define IDS_GENERIC_ERROR               133
#define IDD_DIALOG_DELETE_PROGRESS      134
#define IDS_KB_SUFFIX                   134
#define IDD_CONFIRM_DELETE              135
#define IDS_WAITING                     135
#define IDD_ERROR                       136
#define IDS_COL_FILENAME                136
#define IDD_DIALOG_MOVE_PROGRESS        137
#define IDS_CONFIRM_COPY                137
#define IDD_OPTIONS_DIALOG              138
#define IDS_CONFIRM_MOVE                138
#define IDS_CONFIRM_COPY_PROMPT_TEMPL   139
#define IDS_CONFIRM_MOVE_PROMPT_TEMPL   140
#define IDS_FULLSTOP                    141
#define IDS_CONFIRM_RECYCLE             142
#define IDS_CONFIRM_RECYCLE_PROMPT      143
#define IDS_NOT_STANDALONE              144
#define IDS_MINUTES_ETA_TEMPLATE        145
#define IDS_COPY_N_OF                   146
#define IDS_SECONDS_ETA_TEMPLATE        146
#define IDC_FRAME_ARCHIVE               1000
#define IDC_CHECK_ARCHIVE_ONLY          1001
#define IDC_BUTTON_SKIP                 1001
#define IDC_CHECK_CLEAR_ARCHIVE_BIT     1002
#define IDC_WARNING                     1002
#define IDC_RADIO_OVERWRITE_MAKE_UNIQUE_NAME 1003
#define IDC_BUTTON_MAKE_UNIQUE_NAME     1004
#define IDC_BUTTON_START_NOW            1005
#define IDC_LABEL_WAIT_PREVIOUS         1006
#define IDC_FRAME_OVERWRITE             1007
#define IDC_INFO_ICON                   1007
#define IDC_RADIO_OVERWRITE_ALWAYS      1008
#define IDC_RADIO_OVERWRITE_NEWER       1009
#define IDC_RADIO_OVERWRITE_NEVER       1010
#define IDC_RADIO_OVERWRITE_PROMP       1011
#define IDC_RADIO_OVERWRITE_PROMPT      1011
#define IDC_RADIO_OVERWRITE_POSTPONE    1012
#define IDC_FRAME_OPTIONS               1013
#define IDC_CHECK_CLEAR_READ_ONLY_BIT   1014
#define IDC_CHECK_OPT_OVERWRITE_READ_ONLY 1015
#define IDC_CHECK_SKIP_INVENTORY        1016
#define IDC_BUTTON_YES                  1018
#define IDC_BUTTON_NO                   1019
#define IDC_NEWER                       1020
#define IDC_CHECK_APPLY_TO_ALL          1021
#define IDC_TITLE_LINE                  1022
#define IDC_SIZE1                       1023
#define IDC_DATE1                       1024
#define IDC_ICON1                       1025
#define IDC_FILE_LIST                   1026
#define IDC_SIZE2                       1027
#define IDC_DATE2                       1028
#define IDC_ICON2                       1029
#define IDC_PROMPT                      1045
#define IDC_EDIT_ERRORS                 1047
#define IDC_CHECK_USE_PERIGEECOPY_BY_DEFAULT 1048
#define IDC_PROMPT_CONFIRM_DELETE       1049
#define IDC_PROMPT_DEBUG                1050
#define IDC_PROMPT_RECYCLE              1051
#define IDC_CHECK_WAIT_FOR_PREVIOUS_JOBS 1052
#define IDC_PROGRESS_FILE               1055
#define IDC_PROGRESS_JOB                1056
#define IDC_LBL_SOURCE                  1057
#define IDC_LBL_DEST                    1058
#define IDC_LBL_FILENUM                 1059
#define IDC_LBL_FILECNT                 1060
#define IDC_LBL_KBCOPIED_FILE           1061
#define IDC_LBL_KBCOPIED_JOB            1062
#define IDC_LBL_KBTOTAL_FILE            1063
#define IDC_LBL_KBTOTAL_JOB             1064
#define IDC_LBL_KB_PER_SEC_FILE         1065
#define IDC_LBL_KB_PER_SEC_JOB          1066
#define IDC_CHECK_SKIP_ERROR_FILES      1067
#define IDC_LBL_ETA_FILE                1067
#define IDC_LBL_DELETING                1068
#define IDC_LBL_ETA_JOB                 1068
#define IDC_PROGRESS                    1069
#define IDC_LBL_FILE_DEL                1070
#define IDC_LBL_FILE_TOTAL              1071
#define IDC_TRYAGAIN                    1071
#define IDC_LBL_FOLDER_DEL              1072
#define IDC_SKIPFILE                    1072
#define IDC_LBL_FOLDER_TOTAL            1073
#define IDC_SKIPALL                     1073

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
